name: Run Flask API without Docker

on:
  push:
    branches: [ main ]

jobs:
  run-flask-api:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start Flask API
        shell: powershell
        run: |
          $env:FLASK_APP = "API.py"
          $env:FLASK_ENV = "development"
          Start-Process powershell -ArgumentList "-NoProfile", "-WindowStyle Hidden", "-Command", "flask run --host=127.0.0.1 --port=5000" -PassThru | Set-Content -Path flask_process.txt
          Start-Sleep -Seconds 3

      - name: Wait for API to start
        shell: powershell
        run: |
          $maxRetries = 10
          $i = 0
          do {
            try {
              $resp = Invoke-WebRequest -Uri http://127.0.0.1:5000/health -UseBasicParsing -TimeoutSec 3
              if ($resp.StatusCode -eq 200) {
                Write-Host "API is up!"
                break
              }
            } catch {
              Write-Host "Waiting for API to start..."
              Start-Sleep -Seconds 3
            }
            $i++
          } while ($i -lt $maxRetries)
          if ($i -eq $maxRetries) {
            Write-Error "API did not start in time"
            exit 1
          }

      - name: Encode test image to base64
        shell: powershell
        run: |
          $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes("test-data/face.jpg"))
          echo "IMAGE_B64=$b64" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Test /verify endpoint
        shell: powershell
        run: |
          $json = @{ user_id = "test"; image = $env:IMAGE_B64 } | ConvertTo-Json -Depth 10
          $response = Invoke-RestMethod -Uri http://127.0.0.1:5000/verify -Method POST -Body $json -ContentType "application/json"
          Write-Host "Response from API:"
          $response | ConvertTo-Json -Depth 10

      - name: Kill Flask API
        shell: powershell
        run: |
          $proc = Get-Content flask_process.txt
          Stop-Process -Id $proc.Id -Force
